sudo: true
git:
  depth: 1
branches:
  only:
    - master

matrix:
  include:
    - name: "Ant Mac IOS Build"
      if: type != pull_request
      language: java
      os: osx
      before_install:
        - brew update
        - brew install ant
      install:
        - true
      script:
        - ant -f build-mac-ios.xml
    - name: "Unit test java build"
      if: type != pull_request
      language: java
      os: linux
      before_install:
      - true
      install:
      - ./gradlew assemble
      script:
      - ./gradlew build
    - name: "Unit Tests Android"
      language: android
      android:
        components:
          - build-tools-25.0.3
          - android-25
        licenses:
          - 'android-sdk-license-.+'
      before_install:
        - yes | sdkmanager "platforms;android-27"
      install:
        - ./gradlew assemble
      script:
        - ./gradlew test
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
