/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NztGdx;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.nzt.NztGdxLibrary;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        NztGdxLibrary classUnderTest = new NztGdxLibrary();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
